Set-Location ub-graphitea
vagrant up
Set-Location ../ub-graphitemc
vagrant up
Set-Location ../ub-riemanna
vagrant up
Set-Location ../ub-riemannmc
vagrant up
Set-Location ../host1
vagrant up
Set-Location ../
