#!/bin/bash
cd ub-riemanna
vagrant suspend
cd ../centos-riemannb
vagrant suspend
cd ../ub-riemannmc
vagrant suspend
cd ../ub-graphitea
vagrant suspend
cd ../centos-graphiteb
vagrant suspend
cd ../ub-graphitemc
vagrant suspend
cd ../host2
vagrant suspend
cd ../host2
vagrant suspend
cd ../ela1
vagrant suspend
cd ../ela2
vagrant suspend
cd ../ela3
vagrant suspend
cd ../logstash
vagrant suspend
cd ../tornado-proxy
vagrant suspend
cd ../tornado-web1
vagrant suspend
cd ../tornado-web2
vagrant suspend
cd ../tornado-api1
vagrant suspend
cd ../tornado-api2
vagrant suspend
cd ../tornado-db
vagrant suspend
cd ../tornado-redis
vagrant suspend
cd ../
