# These are your values that would be in arguments.txt
imageid                = ""
instance-type          = ""
key-name               = ""
vpc_security_group_ids = ""
cnt                    = 
install-env-file       = ""
elb-name               = ""
tg-name                = ""
asg-name               = ""
lt-name                = ""
module-tag             = ""
raw-s3                 = ""
finished-s3            = ""
dynamodb-table-name    = ""
ebs-size               = ""
