Set-Location ub-riemanna
vagrant suspend
Set-Location ../centos-riemannb
vagrant suspend
Set-Location ../ub-riemannmc
vagrant suspend
Set-Location ../ub-graphitea
vagrant suspend
Set-Location ../centos-graphiteb
vagrant suspend
Set-Location ../ub-graphitemc
vagrant suspend
Set-Location ../host2
vagrant suspend
Set-Location ../host2
vagrant suspend
Set-Location ../
