########## Inserted by Jeremy
export JAVA_HOME=/usr
export HADOOP_HOME=/home/controller/hadoop-2.8.5
export PIG_HOME=/home/controller/pig
export SPARK_HOME=/home/controller/spark
export MAHOUT_HOME=/home/controller/mahout
export SQOOP_HOME=/home/controller/sqoop
export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$PIG_HOME/bin:$SPARK_HOME/bin:$SPARK_HOME/sbin:$MAHOUT_HOME/bin
export HADOOP_CLASSPATH=/usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar:$SQOOP_HOME/sqoop-1.4.7.jar:/home/controller/mysql-connector-java-5.1.44/mysql-connector-java-5.1.44-bin.jar
export HADOOP_USER_CLASSPATH_FIRST=true
